### PR TITLE
add support for custom type converters

### PR DESCRIPTION
**Pull request by NoUsername**
Hy, thanks for creating SansOrm, I really like the Idea and the Simplicity. One thing I am missing (or just haven't understood how it would be done) is how you would support more types.

What do you think of this little demo implementation of type converters? The Interface is heavily inspired by what Hibernate offers.

I created it to get a little demo with Postgres JSONB Type up and running, this would be the JSONB Converter:
```
package at.paukl.springplay.domain.converter;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.zaxxer.sansorm.Converter;
import org.postgresql.util.PGobject;

import java.io.IOException;
import java.util.Map;

/**
 * @author Paul Klingelhuber
 */
public class PostgresJsonConverter implements Converter<Map, PGobject> {

    private static final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public Map fromDb(PGobject dbValue) {
        try {
            return objectMapper.readValue(dbValue.getValue(), Map.class);
        } catch (IOException e) {
            throw new RuntimeException("problem reading json object", e);
        }
    }

    @Override
    public PGobject toDb(Map javaValue) {
        PGobject pGobject = new PGobject();
        pGobject.setType("jsonb");
        try {
            pGobject.setValue(objectMapper.writeValueAsString(javaValue));
        } catch (Exception e) {
            throw new RuntimeException("problem with json object", e);
        }
        return pGobject;
    }
}
```

and this is an example class using it:

```
@Table(name="users")
public class User {
    @Id
    @Column(name="id")
    public UUID id = UUID.randomUUID();

    @Column(name="username")
    public String username;

    @Column(name="email")
    public String email;

    @Column(name="active")
    public boolean active;

    @Column(name="config")
    @Convert(converter = PostgresJsonConverter.class)
    public Map config;
}
```

### CODE REVIEW

**Comment by lfbayer** [comment]
Thanks for the Pull Request, I like this idea.

JPA already defines a `javax.persistence.Convert` and `javax.persistence.Converter` class. Can this be changed to use them?

Using JPA classes means that the actual objects don't need to have a dependency on sansorm, and also it is presumably a little more portable. If a user already has a class they are using with Hibernate or some other ORM, then using the same annotations means they don't have to change their objects at all.

**Comment by NoUsername** [comment]
I would be all for using standard classes/interfaces when available.
There's only one problem, I can't seem to find the right dependency that would be required for this.
Until now i only had `javax.persistence:persistence-api:1.0` as a dependency in my project, it looks to me that `javax.persistence.Convert` is only part of some other java ee 6/7 spec.

I could very possibly be wrong, but could it be that such a dependency would require some java ee container? Which would mean that you could no longer use SansOrm in e.g. a small Tomcat or Jetty app? (My demo app is a small spring boot application with Jetty).

If I just didn't find it, please point me in the right direction which dependency this would need and I'll make the code changes.

Thank you for your feedback.

**Comment by lfbayer** [comment]
It looks like those classes were adding in javax.persistence 2.1

We would have to update the dependency for SansOrm to be able to pull these annotations. From my point of view I don't see any problem requiring this dependency. What do you think?

**Comment by NoUsername** [comment]
If I'm not mistaken this would require switching from http://mvnrepository.com/artifact/javax.persistence/persistence-api to http://mvnrepository.com/artifact/org.eclipse.persistence/javax.persistence

I don't know enough about the javax.persistence spec/dependencies to know what the difference between the "javax.persistence" and the "org.eclipse.persistence" are (if switching to that could be a problem).

Your call :)

**Comment by lfbayer** [comment]
EclipseLink is the reference implementation for JPA now, so org.eclipse.persistence is actually now the official source for that API. The javax.persistence maven groupId would appear to be from Sun before Oracle bought them out.

You can go ahead and update the dependency to org.eclipse.persistence:javax.persistence:2.1

**Comment by NoUsername** [comment]
Thank you for your help, I've updated the merge request.

**Pull request merged**
