### PR TITLE
Problem with upper case column names #22

### PR DESCRIPTION
**Pull request by h-thurow**
To prevent identifiers from being lower cased by SansOrm, you can now enclose them in quotes, e. g. `@Column(name = "\"FIELD_NAME\"")` SansOrm will than behave like most databases and will leave them as is.  The usage of double quotes for this seems to be common practice.

### CODE REVIEW

**Comment by h-thurow** [comment]
Hello Brett, when do you think that you can review my PR, so we know, if we can utilize SansOrm in production?

**Comment by brettwooldridge** [comment]
SansORM v3.3 has been published.

**Comment by h-thurow** [comment]
Thanks a lot!

**Comment by h-thurow** [comment]
@brettwooldridge There is still inconsistent behaviour wird @Id columns. Especially

`@Id String Id2`

will result in "id2", not "Id2". See CaseSensitiveDatabasesTest#getIdColumnNames(). This seems not to comply with sergiorussia's explanation "all entities in my project are annotated using only standard JPA annotations, and rely on the documented behavior that maps empty Table and Column names to entity and field names accordingly" (see PR #12).

sergiorussia's work "making Introspector case-insensitive regarding column names" (PR #12) is a big improvement. Beyond that I would propose to take the column and table names as is when building the SQL statements, that is not to lower case them. So in case of case sensitive databases (and in our case ;-)) one could avoid the double quotes at all. And with case insensitve databases it does not matter.

**Comment by brettwooldridge** [comment]
Is an ``@Id`` without a ``@Column`` valid?  I don’t have the spec in front of me.

**Comment by h-thurow** [comment]
I am just a JPA novice, but found these examples in "JBoss Enterprise Application Platform 4.2
Hibernate Annotations Reference Guide":

```
@Id @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_STORE")
public Integer getId() { ... }
```
```
@Entity
public class Flight implements Serializable {
    Long id;

    @Id
    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }
}
```

**Pull request merged**
